import { AlertTriangle, CheckCircle2, CircleHelp, FileText, Users } from "lucide-react";
import { useState } from "react";
import type { PersonRiskProfile } from "../../api/persons";

function formatDate(value: string | null | undefined) {
  if (!value) return "Date unavailable";
  return new Date(value).toLocaleString();
}

export default function RiskProfile({ risk }: { risk: PersonRiskProfile }) {
  const [severityFilter, setSeverityFilter] = useState("all");
  const visibleAnomalies = severityFilter === "all" ? risk.anomalies : risk.anomalies.filter((anomaly) => anomaly.severity === severityFilter);
  return <section className="risk-profile" id="risk-profile" aria-labelledby="risk-profile-title">
    <div className="risk-profile-heading"><div><p className="eyebrow">Intelligence review</p><h2 id="risk-profile-title">Person Risk Profile</h2><p>Risk indicators are data-quality and anomaly signals, not conclusions about criminality.</p></div><span className={`risk-band risk-band-${risk.band}`}>{risk.band} triage</span></div>
    <div className="risk-summary-grid"><article className={`risk-score-card risk-score-${risk.band}`}><span>Risk Score</span><strong>{risk.score}<small>/100</small></strong><p>{risk.method}</p></article><article className="risk-count-card"><AlertTriangle size={21}/><div><span>Anomalies</span><strong>{risk.anomalies.length}</strong><small>verified anomaly records</small></div></article><article className="risk-count-card"><Users size={21}/><div><span>Associations</span><strong>{risk.associations.length}</strong><small>factual graph associations</small></div></article><article className="risk-count-card"><FileText size={21}/><div><span>Previous Cases</span><strong>{risk.cases.length}</strong><small>verified source records</small></div></article></div>
    <div className="risk-profile-grid"><article className="data-panel"><h3>Contributing factors</h3><div className="risk-factor-list">{risk.factors.map((factor) => <div key={factor.name}><span>{factor.name}</span><strong>{factor.value}{factor.unit === "%" ? "%" : ` ${factor.unit}`}</strong></div>)}</div><p className="risk-disclaimer"><CircleHelp size={16}/>Community/group association is shown separately and is never used as a risk factor.</p></article><article className="data-panel"><h3>Risk history</h3>{risk.history.length ? risk.history.map((point) => <div className="risk-history-row" key={point.date}><span>{formatDate(point.date)}</span><strong>{point.score}/100</strong></div>) : <div className="risk-empty"><CheckCircle2 size={18}/><span>No historical risk scores are available.</span></div>}</article></div>
    <article className="data-panel risk-anomalies"><div className="risk-section-heading"><h3>Anomalies and unusual activity</h3><label>Severity<select value={severityFilter} onChange={(event) => setSeverityFilter(event.target.value)}><option value="all">All severities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label></div>{risk.anomalies.length ? visibleAnomalies.length ? <div className="risk-anomaly-list">{visibleAnomalies.map((anomaly) => <details className={`risk-anomaly severity-${anomaly.severity}`} key={anomaly.id}><summary><span className={`severity-pill severity-${anomaly.severity}`}>{anomaly.severity}</span><strong>{anomaly.type}</strong><small>{formatDate(anomaly.date)} · {anomaly.transaction_id}</small></summary><div><p><b>Amount:</b> {anomaly.amount.toLocaleString()} {anomaly.channel ? `· ${anomaly.channel}` : ""}</p><p><b>Reason:</b> {anomaly.reason || "No reason recorded."}</p><p><b>Model score:</b> {Math.round(anomaly.score * 100)}%</p></div></details>)}</div> : <div className="risk-empty"><CheckCircle2 size={18}/><span>No anomalies match this severity filter.</span></div> : <div className="risk-empty"><CheckCircle2 size={18}/><span>No verified anomalies detected for this person.</span></div>}</article>
    <div className="risk-profile-grid"><article className="data-panel"><h3>Community and group associations</h3>{risk.associations.length ? <div className="risk-association-list">{risk.associations.map((association) => <div key={association.id}><strong>{association.label}</strong><span>{association.type} · {association.source}</span></div>)}</div> : <div className="risk-empty"><Users size={18}/><span>No verified association data available.</span></div>}</article><article className="data-panel"><h3>Previous cases and incidents</h3>{risk.cases.length ? <div className="risk-case-list">{risk.cases.map((item) => <details key={item.id}><summary><strong>{item.title}</strong><small>{item.id} · {item.status}</small></summary><p>{item.summary || "No additional source summary."}</p><small>Source: {item.source} · Confidence: {Math.round(item.confidence * 100)}%</small></details>)}</div> : <div className="risk-empty"><FileText size={18}/><span>No verified data available. No criminal history is inferred.</span></div>}</article></div>
  </section>;
}
