import {useRef,useState,type DragEvent,type ChangeEvent} from "react";
import {CheckCircle2,FileUp,Upload, XCircle} from "lucide-react";
import {api} from "../api/client.ts";
import {useLanguage} from "../i18n/LanguageContext";
export default function Documents(){
 const {t}=useLanguage();const inputRef=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [progress,setProgress]=useState(0);const [dragging,setDragging]=useState(false);
 function choose(next:File|null){setFile(next);setStatus("");setProgress(0);}
 function handleFiles(files:FileList|null){choose(files?.[0]??null);}
 function onDrop(event:DragEvent<HTMLLabelElement>){event.preventDefault();setDragging(false);handleFiles(event.dataTransfer.files);}
 function onChange(event:ChangeEvent<HTMLInputElement>){handleFiles(event.target.files);}
 function formatSize(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/(1024*1024)).toFixed(1)} MB`;}
 function valid(next=file){return Boolean(next&&next.size&&next.size<=10*1024*1024&&/\.(pdf|txt|csv|json)$/i.test(next.name));}
 async function upload(){if(!valid()){setStatus("uploadInvalid");return;}setBusy(true);setProgress(0);setStatus("");try{const data=new FormData();data.append("file",file as File);await api.post("/documents/upload",data,{headers:{"Content-Type":"multipart/form-data"},onUploadProgress:event=>{if(event.total)setProgress(Math.round((event.loaded/event.total)*100));}});setProgress(100);setStatus("uploadSuccess");}catch{setStatus("error");}finally{setBusy(false);}}
 return <div className="workspace-page evidence-intake-page"><div><p className="eyebrow">Evidence workspace</p><h1>Evidence Intake</h1><p>{t("uploadHelp")}</p></div><section className="settings-card upload-card"><div className="upload-card-heading"><span className="upload-icon"><FileUp size={25}/></span><div><h2>Upload Evidence</h2><p>Bring a source file into your authorized workspace.</p></div></div><label className={`upload-dropzone ${dragging?"is-dragging":""}`} htmlFor="evidence-file" onDragOver={event=>{event.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={onDrop} tabIndex={0} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();inputRef.current?.click();}}}><Upload size={30}/><strong>Drag &amp; drop evidence here or click to browse</strong><span>Supported: PDF, TXT, CSV, JSON · Maximum size: 10 MB</span><input ref={inputRef} id="evidence-file" type="file" accept=".pdf,.txt,.csv,.json" onChange={onChange}/></label>{file&&<div className="selected-upload"><span className="selected-upload-icon"><FileUp size={18}/></span><div><strong>{file.name}</strong><small>{formatSize(file.size)}</small></div><button type="button" className="clear-upload" onClick={()=>choose(null)} aria-label="Remove selected file"><XCircle size={19}/></button></div>}{busy&&<div className="upload-progress" role="status"><div className="upload-progress-label"><span>Uploading evidence</span><strong>{progress}%</strong></div><div className="upload-progress-track"><span style={{width:`${progress}%`}}/></div></div>}<button className="primary-action upload-submit" disabled={!file||busy} onClick={()=>void upload()}><Upload size={17}/>{busy?"Uploading...":"Upload Evidence"}</button>{status==="uploadSuccess"&&<p className="upload-feedback success" role="status"><CheckCircle2 size={18}/>{t(status)}</p>}{status&&status!=="uploadSuccess"&&<p className="upload-feedback error" role="alert"><XCircle size={18}/>{t(status)}</p>}</section></div>;
}
