import {useLanguage} from "../i18n/LanguageContext";
const copy={
en:{
privacy:["Privacy policy","This is an investigation prototype for authorized demonstration use.","Data use","The bundled public FIR corpus is used for relationship lookup. Uploaded file metadata and saved questions are associated with the signed-in account.","Access and review","Do not use live sensitive records until access controls, retention rules and deployment security have been independently reviewed. Outputs are leads, not verdicts."],
terms:["Terms of use","Use only data that you are authorized to access.","Prototype limitations","The current backend performs record search. Uploaded contents are not yet ingested into the graph. It is not a certified production policing system.","Responsibility","Verify every result against original evidence. Scores and connections do not establish guilt."],
cookies:["Cookie policy","No advertising or analytics cookies are added by this prototype.","Essential storage","An HttpOnly cookie holds the session. Browser storage keeps theme, language and tutorial preferences. A tab marker determines whether the login screen is shown.","Your control","Sign out to clear the browser session cookie. Clear browser storage to reset appearance and language. Server records require a separate authorized retention process."]
},
hi:{
privacy:["गोपनीयता नीति","यह अधिकृत प्रदर्शन के लिए जांच प्रोटोटाइप है।","डेटा उपयोग","सार्वजनिक FIR डेटा का उपयोग संबंध खोजने में होता है। अपलोड मेटाडेटा और सहेजे गए प्रश्न खाते से जुड़े हैं।","पहुंच और समीक्षा","स्वतंत्र सुरक्षा, पहुंच और संरक्षण समीक्षा से पहले संवेदनशील वास्तविक रिकॉर्ड न डालें। परिणाम सुराग हैं, निर्णय नहीं।"],
terms:["उपयोग की शर्तें","केवल अधिकृत डेटा का उपयोग करें।","प्रोटोटाइप की सीमाएं","वर्तमान बैकएंड रिकॉर्ड खोजता है। अपलोड की सामग्री अभी ग्राफ में नहीं जुड़ती। यह प्रमाणित उत्पादन पुलिस प्रणाली नहीं है।","जिम्मेदारी","हर परिणाम को मूल साक्ष्य से जांचें। स्कोर और संबंध दोष सिद्ध नहीं करते।"],
cookies:["कुकी नीति","यह प्रोटोटाइप विज्ञापन या विश्लेषण कुकी नहीं जोड़ता।","आवश्यक संग्रह","HttpOnly कुकी सत्र रखती है। ब्राउज़र संग्रह रूप, भाषा और प्रशिक्षण प्राथमिकताएं रखता है। टैब संकेत तय करता है कि लॉगिन दिखे या नहीं।","आपका नियंत्रण","सत्र कुकी हटाने के लिए साइन आउट करें। प्राथमिकताएं रीसेट करने के लिए ब्राउज़र संग्रह साफ करें। सर्वर रिकॉर्ड के लिए अलग अधिकृत संरक्षण प्रक्रिया आवश्यक है।"]
},
mr:{
privacy:["गोपनीयता धोरण","हे अधिकृत प्रात्यक्षिकासाठी तपास प्रोटोटाइप आहे.","माहितीचा वापर","सार्वजनिक FIR माहिती संबंध शोधण्यासाठी वापरली जाते. अपलोड मेटाडेटा आणि जतन केलेले प्रश्न खात्याशी जोडलेले असतात.","प्रवेश आणि पुनरावलोकन","स्वतंत्र सुरक्षा, प्रवेश आणि माहिती जतन धोरणांच्या पुनरावलोकनापूर्वी संवेदनशील वास्तविक नोंदी वापरू नका. निकाल हे धागेदोरे आहेत, निर्णय नाहीत."],
terms:["वापराच्या अटी","फक्त आपल्याला वापरण्याची परवानगी असलेली माहिती वापरा.","प्रोटोटाइपच्या मर्यादा","सध्याचा बॅकएंड नोंदी शोधतो. अपलोडमधील मजकूर अद्याप ग्राफमध्ये जोडला जात नाही. ही प्रमाणित कार्यरत पोलीस प्रणाली नाही.","जबाबदारी","प्रत्येक निकाल मूळ पुराव्याशी पडताळा. गुण आणि संबंध दोष सिद्ध करत नाहीत."],
cookies:["कुकी धोरण","हा प्रोटोटाइप जाहिरात किंवा विश्लेषण कुकी जोडत नाही.","आवश्यक साठवण","HttpOnly कुकी सत्र ठेवते. ब्राउझर साठवण दृश्य, भाषा आणि मार्गदर्शनाची पसंती ठेवते. प्रवेश पृष्ठ दाखवायचे का हे टॅबची खूण ठरवते.","आपले नियंत्रण","सत्र कुकी हटवण्यासाठी बाहेर पडा. पसंती रीसेट करण्यासाठी ब्राउझर साठवण साफ करा. सर्व्हर नोंदींसाठी स्वतंत्र अधिकृत जतन प्रक्रिया आवश्यक आहे."]
}};
export default function LegalPage({type}:{type:"privacy"|"terms"|"cookies"}){const {language}=useLanguage();const p=copy[language][type];return <section className="workspace-page"><h1>{p[0]}</h1><p>{p[1]}</p><article className="settings-card"><h2>{p[2]}</h2><p>{p[3]}</p></article><article className="settings-card"><h2>{p[4]}</h2><p>{p[5]}</p></article></section>;}
